### ISSUE TITLE
Does not launch on Ubuntu 18.04

### ISSUE THREAD

**Issue by legluondunet** [Kierek/RetroArch-Playlists-Generator#2]
Hello,

when I launch your app, I obtain this error message:

r$ python3 playlist_creator.py 
Traceback (most recent call last):
  File "playlist_creator.py", line 96, in <module>
    main(sys.argv[1:])
  File "playlist_creator.py", line 73, in main
    start_gui()
  File "playlist_creator.py", line 79, in start_gui
    GUIResolver()
  File "/home/romain/Autres_applications/Jeux/Emulateurs/RetroArch/RetroArch-Playlists-Generator/RetroArch-Playlists-Generator/modules/gui_resolver.py", line 47, in __init__
    self.__populate_cores_list__()
  File "/home/romain/Autres_applications/Jeux/Emulateurs/RetroArch/RetroArch-Playlists-Generator/RetroArch-Playlists-Generator/modules/gui_resolver.py", line 60, in __populate_cores_list__
    for core in sorted(os.listdir(self.cores_location)):
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/usr/lib/libretro/'

Thank you for your help.

**Comment by Kierek** [comment]
Do you have any libretro cores installed?
